FROM alpine     

RUN apk update       
RUN apk add --no-cache nodejs-current nodejs-npm vim

RUN mkdir -p /usr/src/app   
WORKDIR /usr/src/app                        

COPY . .

RUN npm install

CMD ["npm start"] 